version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
        environment:
        - PROJECT_NAME=Branch Messenger
        - PROJECT_ID=branch-messenger-120ef
        - CLUSTER_NAME=hello-cluster
        - CLOUDSDK_COMPUTE_ZONE=us-west1-a
    
    working_directory: /go/src/hello-app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: {{ item }}
          with_items:
            - sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update --version 120.0.0
            - sudo /opt/google-cloud-sdk/bin/gcloud --quiet components update --version 120.0.0 kubectl
            - echo $ACCT_AUTH | base64 --decode -i > ${HOME}//gcloud-service-key.json
            - sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            - sudo /opt/google-cloud-sdk/bin/gcloud config set project $PROJECT_ID
            - sudo /opt/google-cloud-sdk/bin/gcloud --quiet config set container/cluster $CLUSTER_NAME
            - sudo /opt/google-cloud-sdk/bin/gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
            - sudo /opt/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials $CLUSTER_NAME
      - run:
          name: run test
          command: {{item}}
          with_items:
            - docker run -d -p 8080:8080 gcr.io/${PROJECT_ID}/hello-web:$CIRCLE_SHA!; sleep10
            - curl --retry 10 --retry-delay 5 -v http://localhost:8080
  deploy:
    machine:
      enabled: true
    working_directory: /go/src/hello-app
    steps:
      - checkout
      
      - run:
          name: build docker image
          command: docker build -t gcr.io/${PROJECT_ID}/hello-app:$CIRCLE_SHA1
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push docker image to gcr
          command: gcloud docker push gcr.io/${PROJECT_ID}/hello-app:$CIRCLE_SHA1
      - run:
          name: patch deployment
          command: kubectl patch deployment hello-web -p '{"spec":{"template":{"spec":{"containers":[{"name":"hello-web","image":"gcr.io/${PROJECT_ID}/hello-web:'"$CIRCLE_SHA1"'"}]}}}}'

workflows: 
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

