version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
        environment:
          - TEST_RESULTS=/tmp/test-results
    
    working_directory: ~/hello-app
    steps:
      - checkout
      - run:
          name: build go app
          command: go build main.go
      - run:
          name: create test dir
          command: mkdir $TEST_RESULTS
      - run:
          name: run test
          command: go test -cover -coverprofile=$TEST_RESULTS/c.out
     
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: $TEST_RESULTS
          destination: test-results
  deploy:
    machine:
      enabled: true
    environment:
      - PROJECT_NAME=Branch Messenger
      - PROJECT_ID=branch-messenger-120ef
      - CLUSTER_NAME=test-cluster
      - CLOUDSDK_COMPUTE_ZONE=us-west1-a
    
    working_directory: ~/hello-app

    steps:
      - checkout
      - run:
          name: Gcloud install
          command: export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
            && echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
            && sudo apt-get update && sudo apt-get install google-cloud-sdk
            && sudo /opt/google-cloud-sdk/bin/gcloud --quiet components install kubectl
            && sudo /opt/google-cloud-sdk/bin/gcloud --quiet components install docker-credential-gcr
      - run:
          name: docker credential configure
          command: docker-credential-gcr configure-docker
      - run:
          name: Setup gcloud environment
          command: echo $ACCT_AUTH | base64 --decode -i > ${HOME}//gcloud-service-key.json
            && gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            && gcloud config set project $PROJECT_ID
            && gcloud --quiet config set container/cluster $CLUSTER_NAME
            && gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
            && gcloud --quiet container clusters get-credentials $CLUSTER_NAME
            && gcloud auth configure-docker 
      - run:
          name: build docker image
          command: docker build -t gcr.io/${PROJECT_ID}/hello-app:$CIRCLE_BUILD_NUM .
     
      - run:
          name: push docker image to gcr
          command: sudo docker push gcr.io/${PROJECT_ID}/hello-app:$CIRCLE_BUILD_NUM
      - run:
          name: patch deployment
          command: kubectl set image deployment/hello-app hello-app=gcr.io/${PROJECT_ID}/hello-app:$CIRCLE_BUILD_NUM

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
