version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
        environment:
        - PROJECT_NAME=Branch Messenger
        - PROJECT_ID=branch-messenger-120ef
        - CLUSTER_NAME=hello-cluster
        - CLOUDSDK_COMPUTE_ZONE=us-west1-a
    
    working_directory: /go/src/hello-app

    steps:
      - checkout

      - run:
          name: Install dependencies 3
          command: echo $ACCT_AUTH | base64 --decode -i > ${HOME}//gcloud-service-key.json
      - run:
          name: Install dependencies 4
          command: gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
      - run:
          name: Install dependencies 5
          command: gcloud config set project $PROJECT_ID
      - run:
          name: Install dependencies 6
          command: gcloud --quiet config set container/cluster $CLUSTER_NAME
      - run:
          name: Install dependencies 7
          command: gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
      - run:
          name: Install dependencies 8
          command: gcloud --quiet container clusters get-credentials $CLUSTER_NAME
  deploy:
    machine:
      enabled: true
    working_directory: /go/src/hello-app
    steps:
      - checkout
      
      - run:
          name: build docker image
          command: docker build -t gcr.io/${PROJECT_ID}/hello-app:$CIRCLE_SHA1
      - run:
          name: docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push docker image to gcr
          command: gcloud docker push gcr.io/${PROJECT_ID}/hello-app:$CIRCLE_SHA1
      - run:
          name: patch deployment
          command: kubectl patch deployment hello-web -p '{"spec":{"template":{"spec":{"containers":[{"name":"hello-web","image":"gcr.io/${PROJECT_ID}/hello-web:'"$CIRCLE_SHA1"'"}]}}}}'

workflows: 
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

